spring.application.name=tarakki-work-management
spring.datasource.url=jdbc:postgresql://localhost:5432/tarakki_local
spring.datasource.username=tarakki
spring.datasource.password=tarakki
spring.datasource.driver-class-name =org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = validate
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=10