spring:
  application:
    name: tarakki-organization-service

member:
  service:
    base-url: http://localhost:8081
cors:
  allowed-origins: http://localhost:5173,http://localhost:5174,http://localhost:5175